from:
https://www.reddit.com/r/VFIO/comments/amqqlz/passthrough_guide_for_fedora_29/etznv9r/

site:
- https://qubitrenegade.com/virtualization/kvm/vfio/2019/07/17/VFIO-Fedora-Notes.html
- http://web.archive.org/web/20200404040128/https://qubitrenegade.com/virtualization/kvm/vfio/2019/07/17/VFIO-Fedora-Notes.html
